services:
  portfolio:
    build:
      context: ./portfolio
    container_name: portfolio-cont
    image: portfolio-im
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    volumes:
      - ./portfolio:/app # Sync local files with the container
      - /app/node_modules # Prevent syncing node_modules (performance boost)
    ports:
      - "3001:80" # Direct debugging if needed
    networks:
      - app-network

  investments:
    build:
      context: ./investments
    container_name: investments-cont
    image: investments-im
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    volumes:
      - ./investments:/app # Sync local files with the container
      - /app/node_modules # Prevent syncing node_modules
    ports:
      - "3002:80" # Direct debugging if needed
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: revproxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Nginx configuration
    depends_on:
      - portfolio
      - investments
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
